version: "3.7"
services:
    db:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: '12345'
            POSTGRES_USER: lytx
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U lytx"]
            interval: 10s
            timeout: 5s
            retries: 5
    web:
        build: .
        depends_on: 
            db:
                condition: service_healthy
        ports:
            - '8080:8080'
volumes: 
    pgdata: